### ISSUE TITLE
How to handle timeout

### ISSUE THREAD

**Issue by mcgrady1** [hdusoftsec/MultiFuzz#1]
The project is very interesting.
But I have a question, how do you handle the timeout problem? I do not find the related description in the paper or source code. I mean, because your test targets are servers, and you need to measure the coverage. Hence, you need to terminate the server or broker (or client(sub)), right? 
Thanks for you response!

**Comment by zyingp** [comment]
During fuzzing, the timeout problem is solved by simply using the "-t" option of AFL, e.g., "-t 20".  

When measuring coverage offline, we may have to manually set some timeout value when replaying the input to the server.  The server does not need to be terminated since the gcov keeps working with different inputs, but we need to terminate the client (e.g., the "nc" client) when time is out.

**Comment by mcgrady1** [comment]
Maybe we are not in the same channel. Firstly, i need to claim that I have set timeout to "1000", but my target progress is a service not a tiny program, so it will not exit except crash or you send a kill signal. Hence, if you don't modify the original logic of afl-fuzz.c, any seed will trigger the timeout logic no matter whether you set the -t option.

**Comment by zyingp** [comment]
I didn't try heavy server programs so restarting the server looks good to me (e.g., fuzzing Eclipse Mosquitto with over 1000 execs/s). Maybe you could try the persistant mode of AFL?

**Comment by mcgrady1** [comment]
So how you restart the server 1000/sec, maybe this is my question, thanks for your quick replay

**Comment by zyingp** [comment]
The Eclipse Mosquitto server does not have heavy initialization logic, and the major bottleneck during fuzzing is socketing (receiving/sending packets). That's one of the reasons why we develop the faster desockmulti component (another reason is for multi-connection). After using desockmulti, the fuzzing speed raises from 100+ to 1000+ per second.

**Comment by mcgrady1** [comment]
I mean, you need to restart the server progress? If so, how you restart the progress 1000/sec? Kill the progress or other methods?

**Comment by zyingp** [comment]
Yes. The server is restarted for every fuzzing input. And, the restarting is done just by AFL. Please check its "-t" option.

**Comment by behnamben** [comment]
I also tried to use Multifuzz with a simple lightftp program but it gives me the timeout error. Seems like the inputs are not getting to the program under test.

**Comment by zyingp** [comment]
@behnamben could Preeny(desock) + AFL work with the lightftp program correctly?  We found that both desock and desockmulti could not work with some servers that do not close finished connection timely.

**Comment by behnamben** [comment]
@zyingp I did try Preeny(desock) on a simple lightftp program and it worked for fuzzing.
